/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-04-15 06:20:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.proj4.controller.ORSView;
import in.co.rays.proj4.util.DataUtility;
import in.co.rays.proj4.controller.ChangePasswordCtl;
import in.co.rays.proj4.util.ServletUtility;
import in.co.rays.proj4.controller.LoginCtl;
import in.co.rays.proj4.bean.UserBean;
import in.co.rays.proj4.controller.ORSView;

public final class ChangePasswordView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1775895642000L));
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1776233971000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("in.co.rays.proj4.controller.ORSView");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.LoginCtl");
    _jspx_imports_classes.add("in.co.rays.proj4.bean.UserBean");
    _jspx_imports_classes.add("in.co.rays.proj4.util.DataUtility");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.ChangePasswordCtl");
    _jspx_imports_classes.add("in.co.rays.proj4.util.ServletUtility");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Change Password</title>\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/logo.png\" sizes=\"16x16\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <form action=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\" method=\"post\">\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\n");
      out.write("<!-- Include jQuery -->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\n");
      out.write("<!-- Include jQuery UI -->\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.min.js\"></script>\n");
      out.write("<!-- Include jQuery UI CSS -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css\">\n");
      out.write("	\n");
      out.write("	\n");
      out.write("<script src=\"/ORSProject-04/js/checkbox.js\"></script>\n");
      out.write("<script src=\"/ORSProject-04/js/datepicker.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<!-- Logo -->\n");
      out.write("	<img src=\"");
      out.print(request.getContextPath());
      out.write("/img/customLogo.jpg\"\n");
      out.write("		align=\"right\" width=\"100\" height=\"40\" border=\"0\">\n");
      out.write("	\n");
      out.write("\n");
      out.write("	");

		UserBean user = (UserBean) session.getAttribute("user");
	
      out.write('\n');
      out.write('	');

		if (user != null) {
	
      out.write("\n");
      out.write("	<h3>\n");
      out.write("		Hi,\n");
      out.write("		");
      out.print(user.getFirstName());
      out.write("\n");
      out.write("		(");
      out.print(session.getAttribute("role"));
      out.write(")\n");
      out.write("	</h3>\n");
      out.write("	<a href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\"><b>My Profile</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\"><b>Change Password</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\"><b>Get Marksheet</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\"><b>Marksheet Merit List</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\"><b>Add User</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\"><b>User List</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\"><b>Add Role</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\"><b>Role List</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\"><b>Add College</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\"><b>College List</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\"><b>Add Student</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\"><b>Student List</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\"><b>Add Marksheet</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\"><b>Marksheet List</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\"><b>Add Course</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\"><b>Course List</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\"><b>Add Subject</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\"><b>Subject List</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\"><b>Add Timetable</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\"><b>Timetable List</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\"><b>Add Faculty</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\"><b>Faculty List</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"doc/index.html\" target=\"blank\"><b>Java Doc</b></a>\n");
      out.write("	<b>|</b>\n");
      out.write("	<a href=\"LoginCtl?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\"><b>Logout</b></a>\n");
      out.write("	");

		} else {
	
      out.write("\n");
      out.write("	<h3>Hi, Guest</h3>\n");
      out.write("	<a href=\"WelcomeCtl\"><b>Welcome</b></a> |\n");
      out.write("	<a href=\"LoginCtl\"><b>Login</b></a>\n");
      out.write("	");

		}
	
      out.write("\n");
      out.write("	<hr>\n");
      out.write("	\n");
      out.write("	");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#footer {\n");
      out.write("	position: fixed;\n");
      out.write("	left: 0;\n");
      out.write("	width: 100%;\n");
      out.write("	bottom: 0;\n");
      out.write("	background-color: white;\n");
      out.write("	color: black;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<div id=\"footer\">\n");
      out.write("		<CENTER>\n");
      out.write("			<hr>\n");
      out.write("			<H3>&copy; 2026 RAYS Technologies | All rights reserved</H3>\n");
      out.write("		</CENTER>\n");
      out.write("	</div>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("        ");
      in.co.rays.proj4.bean.UserBean bean = null;
      bean = (in.co.rays.proj4.bean.UserBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new in.co.rays.proj4.bean.UserBean();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\n");
      out.write("\n");
      out.write("        <div align=\"center\">\n");
      out.write("            <h1 align=\"center\" style=\"margin-bottom: -15; color: navy\">Change Password</h1>\n");
      out.write("\n");
      out.write("            <div style=\"height: 15px; margin-bottom: 12px\">\n");
      out.write("                <h3 align=\"center\">\n");
      out.write("                    <font color=\"green\">\n");
      out.write("                        ");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("\n");
      out.write("                    </font>\n");
      out.write("                </h3>\n");
      out.write("                <h3 align=\"center\">\n");
      out.write("                    <font color=\"red\">\n");
      out.write("                        ");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("\n");
      out.write("                    </font>\n");
      out.write("                </h3>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <input type=\"hidden\" name=\"id\" value=\"");
      out.print(bean.getId());
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"createdBy\" value=\"");
      out.print(bean.getCreatedBy());
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"modifiedBy\" value=\"");
      out.print(bean.getModifiedBy());
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"createdDatetime\" value=\"");
      out.print(DataUtility.getTimestamp(bean.getCreatedDatetime()));
      out.write("\">\n");
      out.write("            <input type=\"hidden\" name=\"modifiedDatetime\" value=\"");
      out.print(DataUtility.getTimestamp(bean.getModifiedDatetime()));
      out.write("\">\n");
      out.write("\n");
      out.write("            <table>\n");
      out.write("                <tr>\n");
      out.write("                    <th align=\"left\">Old Password<span style=\"color: red\">*</span></th>\n");
      out.write("                    <td align=\"center\">\n");
      out.write("                        <input type=\"password\" name=\"oldPassword\" placeholder=\"Enter Old Password\"\n");
      out.write("                            value=\"");
      out.print(DataUtility.getString(request.getParameter("oldPassword") == null ? "" : DataUtility.getString(request.getParameter("oldPassword"))));
      out.write("\">\n");
      out.write("                    </td>\n");
      out.write("                    <td style=\"position: fixed;\">\n");
      out.write("                        <font color=\"red\">\n");
      out.write("                            ");
      out.print(ServletUtility.getErrorMessage("oldPassword", request));
      out.write("\n");
      out.write("                        </font>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <th align=\"left\">New Password<span style=\"color: red\">*</span></th>\n");
      out.write("                    <td align=\"center\">\n");
      out.write("                        <input type=\"password\" name=\"newPassword\" placeholder=\"Enter New Password\"\n");
      out.write("                            value=\"");
      out.print(DataUtility.getString(request.getParameter("newPassword") == null ? "" : DataUtility.getString(request.getParameter("newPassword"))));
      out.write("\">\n");
      out.write("                    </td>\n");
      out.write("                    <td style=\"position: fixed;\">\n");
      out.write("                        <font color=\"red\">\n");
      out.write("                            ");
      out.print(ServletUtility.getErrorMessage("newPassword", request));
      out.write("\n");
      out.write("                        </font>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <th align=\"left\">Confirm Password<span style=\"color: red\">*</span></th>\n");
      out.write("                    <td align=\"center\">\n");
      out.write("                        <input type=\"password\" name=\"confirmPassword\" placeholder=\"Enter Confirm Password\"\n");
      out.write("                            value=\"");
      out.print(DataUtility.getString(request.getParameter("confirmPassword") == null ? "" : DataUtility.getString(request.getParameter("confirmPassword"))));
      out.write("\">\n");
      out.write("                    </td>\n");
      out.write("                    <td style=\"position: fixed;\">\n");
      out.write("                        <font color=\"red\">\n");
      out.write("                            ");
      out.print(ServletUtility.getErrorMessage("confirmPassword", request));
      out.write("\n");
      out.write("                        </font>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <th></th>\n");
      out.write("                    <td></td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <th></th>\n");
      out.write("                    <td align=\"left\" colspan=\"2\">\n");
      out.write("                        <input type=\"submit\" name=\"operation\" value=\"");
      out.print(ChangePasswordCtl.OP_SAVE);
      out.write("\">\n");
      out.write("                        &nbsp;\n");
      out.write("                        <input type=\"submit\" name=\"operation\" value=\"");
      out.print(ChangePasswordCtl.OP_CHANGE_MY_PROFILE);
      out.write("\">\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
